### ISSUE TITLE
直接导入生成好的.bin，可在example2.exe中绘图并测试

### ISSUE THREAD

**Issue by zbx911** [fananchong/NavMeshScene#2]
1.导入recastnavmesh生成的navmesh，在example2.exe中绘图，可测试寻路。
2.动态加入障碍物，影响寻路结果。

**Comment by fananchong** [comment]
.bin 文件已经通过 RecastDemo 处理，转化成邻接凸多边行集合，即已经转成可以用A*算法的数据结构。
已经丢失原 3D 数据，画出来也是很多片地形表面

**Comment by zbx911** [comment]
画出来也是很多片地形表面也可以。
